#
#	S O U R C E S
#

# source: defining spherical gamma source

/gate/source/addSource 						GammaSource
/gate/source/GammaSource/gps/type			Volume
/gate/source/GammaSource/gps/shape			Sphere
/gate/source/GammaSource/gps/radius			0.125 mm
/gate/source/GammaSource/gps/centre 		0. 0. 0. cm
/gate/source/GammaSource/gps/particle		gamma
/gate/source/GammaSource/gps/energytype 	Mono
/gate/source/GammaSource/gps/monoenergy 	{Src_E} keV
/gate/source/GammaSource/setActivity 		{Src_Act}
/gate/source/GammaSource/gps/angtype		iso
/gate/source/GammaSource/gps/mintheta		60. deg
/gate/source/GammaSource/gps/maxtheta 		120. deg
/gate/source/GammaSource/gps/minphi 		150. deg
/gate/source/GammaSource/gps/maxphi 		210. deg

/gate/source/list

/gate/source/GammaSource/gps/confine 		source_vol