#sources

/gate/source/addSource					         TwoGamma
/gate/source/TwoGamma/setActivity		     {Src_Act}
/gate/source/TwoGamma/gps/particle		   gamma
/gate/source/TwoGamma/setType			       backtoback
/gate/source/TwoGamma/gps/energytype	   Mono
/gate/source/TwoGamma/gps/monoenergy	   {Src_E}

/gate/source/TwoGamma/gps/type			     Volume
/gate/source/TwoGamma/gps/shape 		     Cylinder
/gate/source/TwoGamma/gps/radius 		     5.0 mm
/gate/source/TwoGamma/gps/halfz 		     15.0 mm
/gate/source/TwoGamma/gps/centre		     {Phan_Src_XPos} 0. 0. mm
/gate/source/TwoGamma/gps/angtype		     iso
/gate/source/TwoGamma/gps/mintheta 		   85. deg
/gate/source/TwoGamma/gps/maxtheta 		   95. deg
/gate/source/TwoGamma/gps/minphi 		     165. deg
/gate/source/TwoGamma/gps/maxphi 		     195. deg

/gate/source/list
/gate/source/TwoGamma/attachTo           source_vol
