#
#	S O U R C E S
#

# source: Universal
/gate/source/addSource 						UniversalSource

/gate/source/UniversalSource/gps/type		Volume
/gate/source/UniversalSource/gps/shape		Sphere
/gate/source/UniversalSource/gps/radius		0.125 mm

/gate/source/UniversalSource/gps/centre 		0. 0. 0. cm
/gate/source/UniversalSource/gps/particle		{particle}
/gate/source/UniversalSource/gps/energytype 	Mono
/gate/source/UniversalSource/gps/monoenergy 	{SourceEnergy} keV
/gate/source/UniversalSource/setActivity 		{SourceActivity} Bq

/gate/source/UniversalSource/gps/angtype		iso
/gate/source/UniversalSource/gps/mintheta		0. deg
/gate/source/UniversalSource/gps/maxtheta 		180. deg
/gate/source/UniversalSource/gps/minphi 		0. deg
/gate/source/UniversalSource/gps/maxphi 		360. deg

#/gate/source/UniversalSource/gps/angtype		iso
#/gate/source/UniversalSource/gps/mintheta		89. deg
#/gate/source/UniversalSource/gps/maxtheta 		91. deg
#/gate/source/UniversalSource/gps/minphi 		179. deg
#/gate/source/UniversalSource/gps/maxphi 		181. deg

/gate/source/list

/gate/source/UniversalSource/visualize 1000 cyan 5
