#
#       P H Y S I C S
#
/gate/physics/addProcess PhotoElectric
/gate/physics/processes/PhotoElectric/setModel PenelopeModel
#/gate/physics/processes/PhotoElectric/setModel LivermoreModel
#/gate/physics/processes/PhotoElectric/setAugerElectron true
/gate/physics/processes/PhotoElectric/setDeexcitation true

/gate/physics/addProcess Compton
/gate/physics/processes/Compton/setModel PenelopeModel

/gate/physics/addProcess RayleighScattering
/gate/physics/processes/RayleighScattering/setModel PenelopeModel

/gate/physics/addProcess ElectronIonisation
/gate/physics/processes/ElectronIonisation/setModel PenelopeModel e-
/gate/physics/processes/ElectronIonisation/setModel PenelopeModel e+

/gate/physics/addProcess Bremsstrahlung
/gate/physics/processes/Bremsstrahlung/setModel PenelopeModel e-
/gate/physics/processes/Bremsstrahlung/setModel PenelopeModel e+

/gate/physics/addProcess PositronAnnihilation

/gate/physics/addProcess GammaConversion
/gate/physics/processes/GammaConversion/setModel PenelopeModel

/gate/physics/addProcess RadioactiveDecay
    
/gate/physics/addProcess IonIonisation
/gate/physics/processes/IonIonisation/setStepFunction GenericIon 0.1 0.02 mm

/gate/physics/addProcess eMultipleScattering
/gate/physics/processes/eMultipleScattering/setModel Urban95Model e-
/gate/physics/processes/eMultipleScattering/setModel Urban95Model e+
/gate/physics/processes/eMultipleScattering/setGeometricalStepLimiterType e- distanceToBoundary
/gate/physics/processes/eMultipleScattering/setGeometricalStepLimiterType e+ distanceToBoundary

/gate/physics/processList Enabled
/gate/physics/processList Initialized

#
#       C U T S
#

#/gate/physics/processes/PhotoElectric/setDeltaRayCut 	1 keV
#/gate/physics/processes/PhotoElectric/setXRayCut 		1 keV

# not for Gamma_Sphere !!
#/gate/physics/Gamma/SetCutInRegion      SPECThead 0.1 cm
#/gate/physics/Electron/SetCutInRegion   SPECThead 1.0 cm

