#
#	V I S U A L I S A T I O N
#
/vis/open 				OGLSX
/vis/viewer/reset

/vis/viewer/set/viewpointThetaPhi	0 90

/vis/viewer/set/style              	wireframe
#/vis/viewer/set/style				surface

/vis/viewer/zoom					5.
/vis/drawVolume
/vis/viewer/flush
#/tracking/verbose 					0
/tracking/storeTrajectory 			1
#/tracking/storeTrajectory 			0
/vis/scene/add/trajectories
#/vis/scene/add/hits
/vis/scene/endOfEventAction 		accumulate 5
##/vis/scene/endOfRunAction 		accumulate 5
/vis/viewer/update
